spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

app:
  message: "Hello Product New"

eureka:
  instance:
    prefer-ip-address: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7